# Création d'un dictionnaire pour associer le terme FR avec la valeur EN exacte du dataset
traduction_fr = {
    "Maison": "HOUSE",
    "Appartement": "APARTMENT",
    "Maison standard": "STANDARD_HOUSE",
    "Appartement standard": "STANDARD_APARTMENT",
    "Propriété de luxe": "LUXURY_PROPERTY",
    "Appartement spécial": "SPECIAL_APARTMENT",
    "Usage mixte": "MIXED_USE",
    "Maison rurale": "RURAL_HOUSE",
    "Autre": "OTHER",
    "Bon": "GOOD",
    "Comme neuf": "AS_NEW",
    "Juste rénové": "JUST_RENOVATED",
    "À rénover": "TO_RENOVATE",
    "Inconnu": "UNKNOWN",
    "À rafraîchir": "TO_BE_DONE_UP",
    "À restaurer": "TO_RESTORE",
    "Gaz": "GAS",
    "Mazout": "FUELOIL",
    "Électrique": "ELECTRIC",
    "Bois": "WOOD",
    "Pellets": "PELLET",
    "Solaire": "SOLAR",
    "Charbon": "CARBON",
    "Installée": "INSTALLED",
    "Hyper équipée": "HYPER_EQUIPPED",
    "Non installée": "NOT_INSTALLED",
    "USA installée": "USA_INSTALLED",
    "USA non installée": "USA_UNINSTALLED",
    "USA hyper équipée": "USA_HYPER_EQUIPPED",
    "Semi équipée": "SEMI_EQUIPPED",
    "USA semi équipée": "USA_SEMI_EQUIPPED",
    "Non zone inondable": "NON_FLOOD_ZONE",
    "Zone inondable reconnue": "RECOGNIZED_FLOOD_ZONE",
    "Zone inondable possible": "POSSIBLE_FLOOD_ZONE",
    "Possible zone inondable non circonscrite": "POSSIBLE_N_CIRCUMSCRIBED_FLOOD_ZONE",
    "Zone inondable reconnue non circonscrite": "RECOGNIZED_N_CIRCUMSCRIBED_FLOOD_ZONE",
}